services:

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=kmdavidds@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  abdimasa-frontend:
    image: kmdavidds/abdimasa:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.abdimasa-frontend.rule=Host(`abdimasa.tripled.cloud`) || Host(`www.pkktoyomarto.my.id`) || Host(`pkktoyomarto.my.id`)"
      - "traefik.http.routers.abdimasa-frontend.entrypoints=websecure"
      - "traefik.http.routers.abdimasa-frontend.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    
  abdimasa-backend:
    image: kmdavidds/abdimasa-backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.abdimasa-backend.rule=Host(`abdimasa-backend.tripled.cloud`) || Host(`api.pkktoyomarto.my.id`)"
      - "traefik.http.routers.abdimasa-backend.entrypoints=websecure"
      - "traefik.http.routers.abdimasa-backend.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    env_file: ".env"
    restart: always

volumes:
  letsencrypt:
